console.log('');
console.log('==========================================================');
console.log('');
console.log('  shopify-cli-tui se mudo a JSR');
console.log('');
console.log('  Para actualizar, ejecuta:');
console.log('');
console.log('    1. bun remove -g shopify-cli-tui');
console.log('    2. bun add -g @jsr/jacuxx__shopify-tui');
console.log('');
console.log('  Mas info: https://jsr.io/@jacuxx/shopify-tui');
console.log('');
console.log('==========================================================');
console.log('');
